### ISSUE TITLE
python port

### ISSUE THREAD

**Issue by boeddeker** [ehabets/RIR-Generator#1]
Is there an interest for a python port for the RIR-Generator?
I am interested in installing it directly from PyPi.
But it would be nice, when the repository, that pushes to PyPi is the original repo.

When there is a chance that a Pull Request would be accepted, I would prepare one.

**Comment by ehabets** [comment]
Srikanth Raj already ported the RIR Generator to Python. The code is available [here](https://github.com/sri17388/py-RIR-Generator). I would nevertheless be happy to support such initiative and accept the pull request.

**Comment by boeddeker** [comment]
I didn't know that there are more python forks, I will take a look at that repo. I used as initial version [https://github.com/Marvin182/rir-generator](https://github.com/Marvin182/rir-generator).
What do you prefer: matlab and python use the same C++ source file or each works on a copy? 

I will also make some Testcases for the python interface that are testable with Travis CI.

**Comment by ehabets** [comment]
Thank you for sharing the Python implementation!
