### ISSUE TITLE
error using mex rir_generator.cpp

### ISSUE THREAD

**Issue by niloofarmaani1** [ehabets/RIR-Generator#5]
Hi
I have been using your function before and it was fine, now I have downloaded the latest version, after importing the file using mex like this:
mex rir_generator.cpp
I will receive this error:
Building with 'MinGW64 Compiler (C++)'.
Error using mex
C:\Users\AppData\Local\Temp\mex_723928368179636_15160\rir_generator.obj:rir_generator.cpp:(.text+0x3e3):
undefined reference to `computeRIR'
collect2.exe: error: ld returned 1 exit status

could you please give me some hint about what the problem is?
Thanks
All the best
Niloo

**Comment by ehabets** [comment]
Please try "mex rir_generator.cpp rir_generator_core.cpp" as mentioned in the README file.

**Comment by niloofarmaani1** [comment]
thanks a lot 
that solved the problem
