### ISSUE TITLE
Support for putting the microphone outside the room?

### ISSUE THREAD

**Issue by Faitsu** [ehabets/RIR-Generator#8]
Hi there RIR-Generator!

I was playing around with the RIR-Generator and I noticed that we are allowed to place the receiver coordinates to be outside the room.  Are the resulting signals that are being picked up by the receiver accurate despite not being inside the room? If so, is there support for receiving a signal from outside the room parameters? And if not, is there a way to repurpose the code to allow me to pick up accurate audio signals from outside the room?

Thank you!

**Comment by ehabets** [comment]
Thank you for reporting this. It's not a feature, it's a bug. An additional check should be added for the source and receiver positions.

**Comment by yzd2022** [comment]
hi，I would like to ask if the data obtained through RIR can be used for sound source localization

**Comment by ehabets** [comment]
Certainly. You can use the tool to generate RIRs between a sound source and two or more microphones. The microphone signals can be generated by convolving the RIRs with a sound source signal. As the inter-microphone level and phase differences are sufficiently accurately modeled, the microphone signals can be used to develop and evaluate sound source localization methods.

**Comment by yzd2022** [comment]
Thanks, so does it support multiple microphones ？

**Comment by ehabets** [comment]
Correct. You can 1) call rir_generator multiple times with different microphone positions (r) or 2) call rir_generator ones by specifying the parameter r as a matrix with M rows (where M denotes the number of microphones) and three columns (with the x, y, and z coordinates).
